global proc switch_rendering_pipeline()
{
    if(`menu -exists Wisp`)
    {
        deleteUI Wisp;
    }

    global string $gMainWindow;
    setParent($gMainWindow);
    
    menu -label "Wisp" -to true -aob true Wisp;
        menuItem -label "PBR Materials Visualization" -command "wisp_switch_rendering_pipeline(\"-deferred\")";
        menuItem -label "Real-Time Final Render Preview" -command "wisp_switch_rendering_pipeline(\"-hybrid_ray_trace\")";
}